In [1]:
from autodiff import Tensor
import numpy as np

## Tensor

In [2]:
x = Tensor(np.ones((2, 2)))
print(x)

[[1. 1.]
 [1. 1.]]


In [3]:
y = x + 2
print(y)

[[3. 3.]
 [3. 3.]]


In [4]:
z = y * y * 3
out = z.mean()
print(z, out)

[[27. 27.]
 [27. 27.]] 27.0


## Gradients

In [5]:
out.backward()

In [6]:
print(x.grad)

[[4.5 4.5]
 [4.5 4.5]]


In [7]:
x = Tensor(np.random.randn(3))

y = x * 2
while np.linalg.norm(y.item) < 1000:
    y = y * 2
    
print(y)

[-776.028117   -201.70143709  684.83313996]


In [8]:
gradients = Tensor([0.1, 1.0, 0.0001])
y.backward(gradients)

print(x.grad)

[5.12e+01 5.12e+02 5.12e-02]
